name: CI-Laravel-Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Copiar .env de ejemplo
        run: cp .env.example .env

      - name: Instalar dependencias PHP
        run: composer install --no-interaction --prefer-dist

      - name: Generar key de Laravel
        run: php artisan key:generate

      - name: Ejecutar tests
        run: php artisan test

      - name: Construir y desplegar con Docker
        run: docker-compose up --build -d
